### local testing meeting end point
get http://localhost:8000/ping2

###
get https://tamal-app.herokuapp.com/ping2

###
get https://tamal-app.herokuapp.com/meeting/all

###
get http://localhost:8000/meeting/all
